/*
 * server/verso-server.js -- the ONE server-of-one artifact (platform-pivot 02/31).
 *
 * Responsibilities are STRICTLY storage + transport (+ auth + presence/locking in
 * later phases). It NEVER renders: render() stays a pure client-side library in both
 * postures. This module serves the StorageBackend contract (registry / kv / media)
 * over HTTP against the SQLite/WAL store on local disk.
 *
 * ONE artifact, two postures -- the mode flag is the ONLY difference:
 *   - local  : bundled inside the desktop shell, binds 127.0.0.1 only, auth dormant.
 *   - server : same file on-prem (Windows Service behind IIS+ARR), binds host, auth
 *              hooks live (Phase 3 fills them; here they default-allow).
 *
 * Dependency-free: node: builtins only. No external network calls / CDN loads.
 * Secrets come from the config FILE (see index.js), never from code.
 */
"use strict";

var http = require("node:http");
var createStore = require("./store").createStore;
var createBlockStore = require("./block-store").createBlockStore;
var createSyncHub = require("./sync").createSyncHub;
var createSyncRoutes = require("./sync-wire").createSyncRoutes;
var createLockManager = require("./lock-manager").createLockManager;
var createReaper = require("./lock-reaper").createReaper;
var createPresence = require("./presence").createPresence;
var createIdentity = require("./identity").createIdentity;
var createReview = require("./review").createReview;
var authRungs = require("./auth-rungs");
var migrations = require("./migrations");
var ops = require("./ops");

var API = "/api/";
var MAX_BODY = 512 * 1024 * 1024; // 512MB hard guard (a large course with inline media)

function sendJson(res, status, obj) {
  var body = JSON.stringify(obj);
  res.writeHead(status, { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body) });
  res.end(body);
}
// ---- the server-mode bootstrap script (ticket 34) --------------------------
// PURE builder (headless-testable): config + registry json + principal -> the JS text
// the browser executes before store-http.js. See the route for why it exists and why it
// is served in front of the identity boundary.
//
// The server URL is computed IN the browser as location.origin rather than baked in
// here, so the value survives whatever host IIS+ARR presents and needs no config entry.
// It is same-origin by construction, which is also what keeps the app offline-safe.
function jsLit(v) {
  // JSON is valid JS, and escaping "<" makes the result safe to sit inside a <script>
  // even though nothing here is ever HTML-embedded today.
  return JSON.stringify(v === undefined ? null : v).replace(/</g, "\\u003c");
}
function buildBootstrap(config, data, principal) {
  var mode = (config && config.mode) || "local";
  var authRequired = !principal;
  var d = data || {};
  var lines = [
    "/* generated by verso-server (platform-pivot 34) -- do not cache across sessions */",
    "window.__versoServerUrl = window.location.origin;",
    "window.__versoServerMode = " + jsLit(mode) + ";",
    "window.__versoServerAuthRequired = " + (authRequired ? "true" : "false") + ";",
    // Which rung this deployment runs, so the account menu can say HOW the person signed in
    // without guessing. Public and secret-free -- the same value /auth/config serves.
    "window.__versoServerRung = " + jsLit((config && config.__rungName) || "local") + ";",
    "window.__versoServerOrg = " + jsLit((config && ((config.auth && config.auth.organisationName) || config.organisationName)) || null) + ";",
    // A server nobody has set up yet shows the first-run wizard instead of a sign-in page --
    // there is nobody to sign in as. Computed by the caller, which knows the account count.
    "window.__versoFirstRunNeeded = " + ((d && d.firstRunNeeded) ? "true" : "false") + ";"
  ];
  if (principal) {
    // The account menu (platform-pivot 39) is the only place a person can confirm WHICH
    // account they are using, so the principal carries what it takes to answer that: the
    // email, the role's admin-defined NAME, and whether this is the emergency account. The
    // capability list is deliberately NOT sent -- the menu shows a role name and never claims
    // a capability meaning, and the server decides permissions regardless of what the page holds.
    lines.push("window.__versoServerPrincipal = " + jsLit({
      kind: principal.kind, role: principal.role, name: principal.name,
      email: principal.email || null, breakGlass: !!principal.breakGlass
    }) + ";");
    // The four facets the StorageBackend declares, inlined. Each is ABSENT rather than
    // empty when the server holds nothing, so the client can tell "server has nothing
    // yet" from "server did not answer" -- the difference between seeding a fresh install
    // and silently discarding somebody's work.
    var b64 = function (s) { return Buffer.from(String(s), "utf8").toString("base64"); };
    if (d.registry != null) lines.push("window.__versoServerRegistryB64 = " + jsLit(b64(d.registry)) + ";");
    if (d.products != null) lines.push("window.__versoServerProductsB64 = " + jsLit(b64(d.products)) + ";");
    if (d.library != null) lines.push("window.__versoServerLibraryB64 = " + jsLit(b64(d.library)) + ";");
    if (d.classification != null) lines.push("window.__versoServerClassificationB64 = " + jsLit(b64(d.classification)) + ";");
  }
  return lines.join("\n") + "\n";
}

// ---- assembling the shared library (platform-pivot 32) ----------------------
// The library is stored DECOMPOSED: the components blob under a kv key, and each source
// document's body as block-addressable rows under doc id "src:<masterId>". That split is
// the whole point -- two authors in two different source documents no longer rewrite each
// other's work on every save (see src/source-doc.js's uio-W17 note).
//
// Reassembly uses the app's OWN src/source-doc.js rather than a copy of its mapping. A
// second implementation of fromBlockDoc living on the server is exactly how two versions
// of "what a source document is" drift apart, and the mark anchors would be what breaks.
// The require is repo-relative, so the server stays free of third-party dependencies.
var SourceDoc = null;
try { SourceDoc = require("../src/source-doc.js"); } catch (e) { SourceDoc = null; }
var SRC_DOC_PREFIX = "src:";
function libraryDocId(masterId) { return SRC_DOC_PREFIX + masterId; }

// ---- the hydration set (platform-pivot 35) ---------------------------------
// WHY THIS EXISTS. platform-pivot-32 made the library shared and its writes per-node, which was
// the CORRECTNESS half of James's loading decision. This is the SCALING half he actually chose:
// "Products up front, source documents on demand. Source documents are the big, growing pile --
// they load as you open them. Start stays fast as the library grows."
//
// THE CONSTRAINT THAT DECIDES THE DESIGN. `readLibrary()` is synchronous by the seam's contract,
// and src/editor/source-link.js's render resolver reads `master.doc` DURING canvas render for
// every source-linked block in the open design document. So "load a source document when the
// author opens it" is not sufficient on its own: a design document's first render depends on the
// bodies of every source document it links into, and a body that is not there yet renders a
// BLANK BLOCK -- which does not look like an error, it looks like empty content. That is the
// worst failure mode available here.
//
// So the bootstrap ships the library SHELL (every master's metadata, topic bodies omitted) plus
// the bodies of exactly the set the first render can need, computed here where the documents
// already are. Everything else is fetched on demand by GET /api/library/topic/:id.
//
// PURE (registry + open-doc ids in, id set out) so the rule is testable without a store.
function hydrationSet(registry, openDocIds) {
  var need = Object.create(null);
  var docs = [];
  if (registry && typeof registry === "object") {
    var ids = (Array.isArray(openDocIds) && openDocIds.length) ? openDocIds : Object.keys(registry);
    ids.forEach(function (id) { if (registry[id]) docs.push(registry[id]); });
  }
  docs.forEach(function (d) {
    (function walkPages(doc) {
      ((doc && doc.pages) || []).forEach(function (p) {
        (function walk(list) {
          (list || []).forEach(function (b) {
            if (!b || typeof b !== "object") return;
            if (b.sourceLink && b.sourceLink.masterId) need[b.sourceLink.masterId] = true;
            ["children", "columns", "items", "blocks", "cells"].forEach(function (k) { if (Array.isArray(b[k])) walk(b[k]); });
          });
        })(p.blocks);
      });
    })(d);
  });
  return Object.keys(need);
}

// One topic's body, materialized from its block rows. Null when there are no rows -- the caller
// decides whether that means "keep what the blob had" or "nothing to send".
function topicDoc(blockStore, id) {
  if (!blockStore || !SourceDoc) return null;
  var doc = null;
  try { doc = blockStore.materializeDoc(libraryDocId(id)); } catch (e) { return null; }
  if (!doc) return null;
  try { return SourceDoc.toJSON(SourceDoc.fromBlockDoc(doc)); } catch (e) { return null; }
}

// opts.hydrate = the ids whose bodies to include. Omitted entirely -> every topic is hydrated,
// which is the pre-35 behaviour and what a caller with no open-doc context still gets.
function assembleLibrary(store, blockStore, opts) {
  var raw = null;
  try { raw = store.getKv("authoring.library"); } catch (e) { return null; }
  if (raw == null) return null;
  if (!blockStore || !SourceDoc) return raw; // no block store -> the blob is all there is
  var lib;
  try { lib = JSON.parse(raw); } catch (e) { return raw; }
  var comps = (lib && lib.components) || {};
  var only = (opts && opts.hydrate) ? opts.hydrate : null;
  var wanted = null;
  if (only) { wanted = Object.create(null); only.forEach(function (id) { wanted[id] = true; }); }
  Object.keys(comps).forEach(function (id) {
    var m = comps[id];
    if (!m || m.kind !== "topic") return;
    if (wanted && !wanted[id]) {
      // NOT hydrated. The body is dropped and the master is FLAGGED, so a reader can tell
      // "not loaded yet" from "genuinely empty" -- without the flag, an un-hydrated source
      // document is indistinguishable from one an author emptied, and the app would happily
      // render the blank.
      delete m.doc;
      m.__deferred = true;
      return;
    }
    var body = topicDoc(blockStore, id);
    // A topic whose rows are absent keeps whatever body the blob carried. Dropping it
    // would present an empty source document as a real one, and the author would edit
    // into the void.
    if (body) m.doc = body;
    delete m.__deferred;   // hydrated: never leave a stale "not loaded" mark on a body we sent
  });
  return JSON.stringify(lib);
}

function sendBootstrap(res, config, store, blockStore, principal, identity) {
  var data = {};
  // Asked once, at the top: a server with no accounts is not "signed out", it is un-installed,
  // and showing it a sign-in page is a dead end.
  if (identity) { try { data.firstRunNeeded = ((identity.listUsers({ kind: "system", capabilities: ["manageUsers"] }).users) || []).length === 0; } catch (e) {} }
  if (principal) {
    try { data.registry = store.getRegistry(); } catch (e) {}
    try { data.products = store.getKv("authoring.products"); } catch (e) {}
    // uio-F07: classification levels are deployment-wide and tiny, so they take the products
    // posture exactly. On a shared server they MUST be shared -- a per-client copy would let two
    // authors classify the same content against different rule sets.
    try { data.classification = store.getKv("authoring.classification"); } catch (e) {}
    // Products up front (small, bounded); source documents on demand (the big, growing pile) --
    // except the ones the first render cannot do without. See hydrationSet above.
    try {
      var reg = null, open = null;
      try { reg = JSON.parse(store.getRegistry() || "{}"); } catch (e) { reg = null; }
      try { open = JSON.parse(store.getKv("authoring.openDocIds") || "null"); } catch (e) { open = null; }
      data.library = assembleLibrary(store, blockStore, { hydrate: hydrationSet(reg, open) });
    } catch (e) {}
  }
  var body = buildBootstrap(config, data, principal);
  res.writeHead(200, {
    "Content-Type": "application/javascript; charset=utf-8",
    "Content-Length": Buffer.byteLength(body),
    // The registry changes on every save; a cached bootstrap would boot an author into
    // a stale world. Never cache.
    "Cache-Control": "no-store"
  });
  res.end(body);
}
function readBody(req, cb) {
  var chunks = [], size = 0, tooBig = false;
  req.on("data", function (c) {
    size += c.length;
    if (size > MAX_BODY) { tooBig = true; try { req.destroy(); } catch (e) {} return; }
    chunks.push(c);
  });
  req.on("end", function () { cb(tooBig ? null : Buffer.concat(chunks)); });
  req.on("error", function () { cb(null); });
}
// Read a raw body, replying 413 on an over-size/read failure; else hand the buffer to cb.
function withBody(req, res, cb) {
  readBody(req, function (buf) {
    if (buf === null) return sendJson(res, 413, { ok: false, error: "body too large or read error" });
    cb(buf);
  });
}
// As withBody, but parse the body as JSON, replying 400 on malformed JSON.
function withJsonBody(req, res, cb) {
  withBody(req, res, function (buf) {
    var obj; try { obj = JSON.parse(buf.toString("utf8")); } catch (e) { return sendJson(res, 400, { ok: false, error: "bad json" }); }
    cb(obj, buf);
  });
}

// ---- Identity boundary (ticket 17) ----------------------------------------
function parseCookies(req) {
  var out = {}, c = (req.headers && req.headers.cookie) || "";
  c.split(";").forEach(function (kv) { var i = kv.indexOf("="); if (i > 0) out[kv.slice(0, i).trim()] = decodeURIComponent(kv.slice(i + 1).trim()); });
  return out;
}
// Resolve the principal for a request. Local mode -> a single implicit OWNER with full
// power (admin+author); server mode -> a session cookie (user) or an x-verso-guest token,
// else null (reject). This is the ONE boundary in front of the storage API (AC1).
function principalOf(req, identity, config, rung) {
  if (!config || config.mode !== "server" || !identity) return { principal: "owner", role: "admin", kind: "owner", name: "Owner" };
  var guestTok = req.headers && req.headers["x-verso-guest"];
  if (guestTok) { var g = identity.authorizeGuest(guestTok); if (g) return g; }
  var session = identity.resolveSession(parseCookies(req).verso_session);
  if (session) return session;
  // The IWA rung (ticket 19): IIS has already done Kerberos/NTLM and forwards the account,
  // so there is no sign-in page to visit -- the first request IS the sign-in. The adapter
  // refuses a header that did not come from a configured upstream, so this cannot be used
  // to walk in as anyone; see auth-rungs.js.
  if (rung && rung.isRequestRung) {
    var who = rung.fromRequest(req);
    if (who) {
      var u = identity.findOrCreateUser(who.email, who.name);
      return identity.resolveSession(identity.createSession(u.id));
    }
  }
  return null;
}
// The capability an /api route requires. Reads need `view`; comment routes need `comment`
// (so reviewers + guests may annotate but not edit); review-link routes need `issueLinks`;
// admin file-restore needs an admin-only cap; other writes need `edit`.
function capFor(rest, method) {
  var read = (method === "GET" || method === "HEAD");
  if (/^doc\/[^/]+\/comments/.test(rest)) return read ? "view" : "comment";
  if (/^doc\/[^/]+\/links/.test(rest)) return "issueLinks";
  if (/^doc\/[^/]+\/restore/.test(rest)) return "promote"; // admin-only file-checkpoint restore
  // roles + people (platform-pivot 37): READING them needs manageUsers too. The list is not
  // secret, but it names every account on the server, and only the person who can change it
  // has a reason to see it.
  if (/^(roles|users)(\/|$)/.test(rest)) return "manageUsers";
  return read ? "view" : "edit";
}

// Build the request handler around a store + config. Exported separately so tests can
// drive it without binding a socket. An optional blockStore (ticket 03) mounts the
// block-addressable /api/doc/* routes below the same API -- the boundary Phase-2 sync
// fans out from. When absent, only the ticket-02 blob routes are served.
function makeHandler(store, config, blockStore, sync, identity, review, rung, opsState) {
  opsState = opsState || {};
  config = config || {};
  return function handler(req, res) {
    var raw = req.url || "";
    var qi = raw.indexOf("?");
    var query = qi >= 0 ? raw.slice(qi + 1) : "";
    var url = qi >= 0 ? raw.slice(0, qi) : raw;
    var method = req.method || "GET";

    if (url === "/api/health") {
      // the running artifact version is always identifiable (ticket 27); ?deep=1 adds the
      // readings and the alert evaluation an IT monitor polls less often (platform-pivot 31).
      var deep = /(^|&)deep=1(&|$)/.test(query);
      return sendJson(res, 200, ops.health({
        mode: config.mode, version: migrations.SERVER_VERSION, schemaVersion: migrations.SCHEMA_VERSION,
        dataDir: config.dataDir || (opsState.dbPath && require("node:path").dirname(opsState.dbPath)) || ".",
        blockStore: blockStore, lockManager: opsState.lockManager,
        thresholds: config.thresholds, uptimeSec: Math.round(process.uptime())
      }, deep));
    }

    // --- server-mode bootstrap (ticket 34): THE ON-RAMP. -----------------------
    // Everything server-mode in the client is gated behind window.__versoServerUrl --
    // the HTTP storage adapter (store-http.js:50) and the whole live-collaboration
    // client (sync-client.js:26). Until this route existed nothing anywhere set it, so
    // the backend and the client half were both built, both tested, and not connected.
    //
    // It is a classic <script src>, not a fetch, because that is blocking and ordered:
    // by the time store-http.js runs its globals are already set, which is what satisfies
    // readRegistry()'s synchronous contract WITHOUT this backend rendering a page (it
    // never will -- see the 404 below) and without an async editor boot.
    //
    // IN FRONT OF THE IDENTITY BOUNDARY, deliberately. A 401 here yields an empty script,
    // no globals, and the app silently falls back to browser storage -- the author edits
    // on their own machine believing they are on the server, and strands the work. So the
    // route NEVER 401s: it always says which mode you are in, and withholds only the data.
    if (url === "/api/bootstrap.js") {
      var bp = principalOf(req, identity, config, rung);
      config.__rungName = rung ? rung.name : "local";
      return sendBootstrap(res, config, store, blockStore, bp, identity);
    }

    // --- first run (platform-pivot 31) -----------------------------------------
    // A server with no accounts yet has nothing to protect and nobody who could authenticate,
    // so these two routes sit in FRONT of the identity boundary -- and they close themselves the
    // moment the first admin exists. Leaving them open after that would be a permanent
    // create-an-admin endpoint, which is the obvious way to lose a server.
    if (url === "/api/first-run" && identity) {
      var pending = identity.listUsers({ kind: "system", capabilities: ["manageUsers"] });
      var count = (pending.users || []).length;
      if (method === "GET") {
        return sendJson(res, 200, { ok: true, needed: count === 0, org: (config.auth && config.auth.organisationName) || config.organisationName || null, dataDir: config.dataDir || null });
      }
      if (method === "POST") return withJsonBody(req, res, function (body) {
        if (count > 0) return sendJson(res, 409, { ok: false, error: "this server has already been set up" });
        if (!body.adminEmail || !body.adminPassword) return sendJson(res, 400, { ok: false, error: "the local admin account needs an email and a password" });
        // The break-glass admin is created FIRST, so that even if a later step of first-run
        // fails the server is reachable rather than stranded with no way in.
        identity.ensureBreakGlass(body.adminEmail, body.adminPassword, body.adminName);
        if (body.organisationName) { config.organisationName = String(body.organisationName); }
        if (body.oidc && body.oidc.issuer) { config.auth = Object.assign({}, config.auth, { rung: "oidc", oidc: body.oidc, organisationName: config.organisationName }); }
        if (opsState.log) opsState.log.auth("first-run", { email: body.adminEmail, rung: (config.auth && config.auth.rung) || "local" });
        return sendJson(res, 200, { ok: true, org: config.organisationName || null, rung: (config.auth && config.auth.rung) || "local" });
      });
      return sendJson(res, 405, { ok: false, error: "method not allowed" });
    }

    // --- auth routes (ticket 17; public login/logout; server mode only) ---
    if (url === "/auth/login" && method === "POST" && identity) return withJsonBody(req, res, function (body) {
      var r = identity.login(identity.localAccountsAdapter, { email: body.email, password: body.password });
      // Logged either way, and NEVER with the password: a failed sign-in is the event an admin
      // is most often asked to account for, and the log line is useless if it only records the
      // successes. ops.createLog drops any credential-shaped field by name.
      if (opsState.log) opsState.log.auth(r ? "signin" : "signin-failed", { email: body.email, rung: "local" });
      if (!r) return sendJson(res, 401, { ok: false, error: "invalid credentials" });
      // Secure by default in server mode (on-prem TLS); config.insecureCookie relaxes it
      // for a plain-HTTP test/dev bring-up only.
      var secure = (config.mode === "server" && !config.insecureCookie) ? "; Secure" : "";
      res.setHeader("Set-Cookie", "verso_session=" + r.token + "; HttpOnly; Path=/; SameSite=Strict" + secure);
      return sendJson(res, 200, { ok: true, user: r.user });
    });
    if (url === "/auth/logout" && method === "POST" && identity) {
      var ck = parseCookies(req);
      if (opsState.log) { var who = identity.resolveSession(ck.verso_session); if (who) opsState.log.auth("signout", { email: who.email }); }
      if (ck.verso_session) identity.signOut(ck.verso_session);
      res.setHeader("Set-Cookie", "verso_session=; Path=/; Max-Age=0");
      return sendJson(res, 200, { ok: true });
    }
    if (url === "/auth/me") {
      return sendJson(res, 200, { ok: true, principal: principalOf(req, identity, config, rung) });
    }

    // --- what the sign-in surface needs to know (ticket 19) --------------------
    // Public and secret-free by construction: it names the RUNG and the organisation, never
    // a client id and never a secret. The surface cannot render its five states without it --
    // in particular it cannot tell "this deployment has no SSO" from "the IdP is down", and
    // showing an outage message on a local-accounts-only server would be a lie.
    if (url === "/auth/config" && method === "GET") {
      var org = (config.auth && config.auth.organisationName) || config.organisationName || null;
      var payload = {
        ok: true,
        mode: config.mode || "local",
        org: org,                                   // null -> the surface says "your organisation"
        rung: rung ? rung.name : "local",
        sso: !!(rung && rung.isRedirectRung),       // is there a redirect path to offer at all
        localAccounts: true                         // the floor is always present (break-glass)
      };
      // Reachability is asked for, not assumed. A deployment with SSO configured but an IdP
      // it cannot reach must render the outage state, and the ONLY way to know is to look.
      if (rung && rung.probe) {
        return Promise.resolve(rung.probe()).then(function (p) {
          payload.ssoReachable = !!(p && p.ok);
          return sendJson(res, 200, payload);
        }).catch(function () { payload.ssoReachable = false; return sendJson(res, 200, payload); });
      }
      return sendJson(res, 200, payload);
    }

    // --- the OIDC auth-code round trip (ticket 19) -----------------------------
    // Two routes because that is what the flow is: leave for the IdP, come back with a code.
    // Neither is behind the identity boundary -- they are how a person acquires an identity.
    if (url === "/auth/sso/start" && identity && rung && rung.isRedirectRung) {
      return Promise.resolve(rung.begin("/")).then(function (b) {
        if (!b) return sendJson(res, 503, { ok: false, error: "cannot reach the sign-in service", rung: rung.name });
        res.writeHead(302, { Location: b.url, "Cache-Control": "no-store" });
        return res.end();
      }).catch(function () { return sendJson(res, 503, { ok: false, error: "cannot reach the sign-in service" }); });
    }
    if (url.indexOf("/auth/sso/callback") === 0 && identity && rung && rung.isRedirectRung) {
      var q = {};
      String(query || "").split("&").forEach(function (kv) {
        if (!kv) return; var i = kv.indexOf("="); var k = i < 0 ? kv : kv.slice(0, i);
        q[decodeURIComponent(k)] = i < 0 ? "" : decodeURIComponent(kv.slice(i + 1).replace(/\+/g, " "));
      });
      // An IdP that refuses says so in the query string; pass its reason on rather than
      // rendering a generic failure the admin cannot act on.
      if (q.error) return sendJson(res, 401, { ok: false, error: q.error_description || q.error });
      return Promise.resolve(rung.complete(q.code, q.state)).then(function (r) {
        if (!r || !r.ok) return sendJson(res, 401, { ok: false, error: (r && r.reason) || "sign-in failed" });
        // SSO proved WHO, and stops there. The Verso user record decides what they may do.
        var u = identity.findOrCreateUser(r.identity.email, r.identity.name);
        if (opsState.log) opsState.log.auth("signin", { email: r.identity.email, rung: rung.name });
        var tok = identity.createSession(u.id);
        var sec = (config.mode === "server" && !config.insecureCookie) ? "; Secure" : "";
        res.writeHead(302, {
          "Set-Cookie": "verso_session=" + tok + "; HttpOnly; Path=/; SameSite=Lax" + sec,
          Location: r.returnTo || "/", "Cache-Control": "no-store"
        });
        return res.end();
      }).catch(function (e) { return sendJson(res, 401, { ok: false, error: "sign-in failed: " + (e && e.message || e) }); });
    }

    // --- live-collaboration long-poll fallback (ticket 08; server mode only). Handled
    //     here (NOT under /api/) so it isn't shadowed by the /api 404 below. ---
    if (url === "/sync/send" && method === "POST" && sync) {
      var sp = principalOf(req, identity, config, rung);
      if (!sp) return sendJson(res, 401, { ok: false, error: "authentication required" });
      return withJsonBody(req, res, function (body) {
        sync.handleSend(body.clientId, body.envelope, sp, function (r) { return sendJson(res, r.ok ? 200 : (/authentication/.test(r.error || "") ? 401 : 409), r); });
      });
    }
    if (url === "/sync/poll" && method === "GET" && sync) {
      var pp = principalOf(req, identity, config, rung);
      if (!pp) return sendJson(res, 401, { ok: false, error: "authentication required" });
      var clientId = "";
      (query.split("&")).forEach(function (kv) { var p = kv.split("="); if (p[0] === "clientId") clientId = decodeURIComponent(p[1] || ""); });
      return sync.handlePoll(clientId, pp, function (r) { return sendJson(res, r.ok ? 200 : 401, r); });
    }

    if (url.indexOf(API) !== 0) {
      return sendJson(res, 404, { ok: false, error: "not an API route (this backend never serves the app or renders)" });
    }

    var rest = url.slice(API.length); // e.g. "registry", "kv/authoring.activeDocId", "media/<id>"

    // --- identity boundary (ticket 17): resolve principal-or-reject in front of storage,
    //     then enforce the capability matrix (reads=view, writes=edit; guests scoped). ---
    var principal = principalOf(req, identity, config, rung);
    if (!principal) return sendJson(res, 401, { ok: false, error: "authentication required" });
    req.__principal = principal;
    if (config.mode === "server" && identity) {
      var cap = capFor(rest, method);
      var scope = null;
      if (principal.kind === "guest" && rest.indexOf("doc/") === 0) scope = { docId: decodeURIComponent(rest.slice(4).split("/")[0]) };
      if (!identity.principalCan(principal, cap, scope)) {
        return sendJson(res, 403, { ok: false, error: "not permitted (" + cap + ")", role: principal.role });
      }
    }

    // --- one source document's body, on demand (platform-pivot 35) -------------
    // The other half of the deferred library: the bootstrap ships the shell plus the first
    // render's hydration set, and this fetches the rest as an author opens them. A read, so it
    // needs `view` -- capFor already answers that for any /api route that is not named below.
    if (rest.indexOf("library/topic/") === 0 && method === "GET") {
      var topicId = decodeURIComponent(rest.slice("library/topic/".length));
      if (!topicId) return sendJson(res, 400, { ok: false, error: "missing topic id" });
      var body = topicDoc(blockStore, topicId);
      // A topic with no rows is reported as such rather than as an empty document: the client
      // must be able to tell "there is nothing here" from "this did not load", or it will render
      // a blank and call it content.
      return sendJson(res, 200, { ok: true, id: topicId, doc: body, empty: !body });
    }

    // --- roles + people (platform-pivot 37) ------------------------------------
    // The composition surface pp-21 renders. Every route returns the module's own
    // { ok, error } value rather than translating it: the refusals carry the reason the
    // panel has to show (which invariant, how many holders), and re-wording them here is
    // how a UI ends up explaining a rule the server did not actually apply.
    if (identity && (rest === "roles" || rest.indexOf("roles/") === 0 || rest === "users" || rest.indexOf("users/") === 0)) {
      var seg = rest.split("/").map(decodeURIComponent);
      var refuse = function (r) { return sendJson(res, r.ok ? 200 : (/not permitted/.test(r.error || "") ? 403 : 409), r); };
      if (rest === "roles" && method === "GET") return sendJson(res, 200, identity.listRoles(principal));
      if (rest === "roles" && method === "POST") return withJsonBody(req, res, function (body) {
        return refuse(identity.createRole(principal, { name: body.name, capabilities: body.capabilities }));
      });
      if (rest === "roles/default" && method === "PUT") return withJsonBody(req, res, function (body) {
        return refuse(identity.setDefaultRole(principal, body.roleId));
      });
      if (seg[0] === "roles" && seg.length === 2 && method === "PATCH") return withJsonBody(req, res, function (body) {
        return refuse(identity.updateRole(principal, seg[1], { name: body.name, capabilities: body.capabilities }));
      });
      if (seg[0] === "roles" && seg.length === 2 && method === "DELETE") return refuse(identity.deleteRole(principal, seg[1]));
      if (rest === "users" && method === "GET") return sendJson(res, 200, identity.listUsers(principal));
      if (seg[0] === "users" && seg.length === 3 && seg[2] === "role" && method === "PUT") return withJsonBody(req, res, function (body) {
        return refuse(identity.assignRole(principal, seg[1], body.roleId, null));
      });
      if (seg[0] === "users" && seg.length === 2 && method === "DELETE") return refuse(identity.removeUser(principal, seg[1]));
      return sendJson(res, 405, { ok: false, error: "method not allowed" });
    }

    // --- registry (doc-of-record; blob-level v1) ---
    if (rest === "registry") {
      if (method === "GET") return sendJson(res, 200, { ok: true, registry: store.getRegistry() });
      if (method === "PUT") return withBody(req, res, function (buf) {
        store.setRegistry(buf.toString("utf8"));
        return sendJson(res, 200, { ok: true });
      });
      return sendJson(res, 405, { ok: false, error: "method not allowed" });
    }

    // --- key/value (doc-session keys: active doc, open docs) ---
    if (rest.indexOf("kv/") === 0) {
      var key = decodeURIComponent(rest.slice(3));
      if (!key) return sendJson(res, 400, { ok: false, error: "missing key" });
      if (method === "GET") return sendJson(res, 200, { ok: true, value: store.getKv(key) });
      if (method === "DELETE") { store.deleteKv(key); return sendJson(res, 200, { ok: true }); }
      if (method === "PUT") return withBody(req, res, function (buf) {
        store.setKv(key, buf.toString("utf8"));
        return sendJson(res, 200, { ok: true });
      });
      return sendJson(res, 405, { ok: false, error: "method not allowed" });
    }

    // --- media (heavy assets) ---
    if (rest === "media/sweep") {
      if (method !== "POST") return sendJson(res, 405, { ok: false, error: "method not allowed" });
      return readBody(req, function (buf) {
        var keep = [];
        try { var p = JSON.parse((buf || Buffer.from("{}")).toString("utf8")); keep = (p && p.keep) || []; } catch (e) {}
        return sendJson(res, 200, store.sweepMedia(keep));
      });
    }
    if (rest.indexOf("media/") === 0) {
      var id = decodeURIComponent(rest.slice(6));
      if (!id) return sendJson(res, 400, { ok: false, error: "missing media id" });
      if (method === "HEAD") { res.writeHead(store.hasMedia(id) ? 200 : 404); return res.end(); }
      if (method === "GET") {
        var m = store.getMedia(id);
        if (!m) return sendJson(res, 404, { ok: false, error: "no such media" });
        return sendJson(res, 200, { ok: true, data: m.data, mime: m.mime });
      }
      if (method === "PUT") return withBody(req, res, function (buf) {
        var data = buf.toString("utf8"), mime = null;
        // Accept either a raw data: URL body or a {data,mime} JSON envelope.
        if (data.charAt(0) === "{") { try { var p = JSON.parse(data); data = p.data; mime = p.mime || null; } catch (e) {} }
        store.putMedia(id, data, mime);
        return sendJson(res, 200, { ok: true });
      });
      return sendJson(res, 405, { ok: false, error: "method not allowed" });
    }

    // --- block-addressable doc routes (ticket 03; mounted only when a block store is
    //     wired). The change log crossing here IS the seq-stamped stream Phase 2 fans
    //     out; GET /changes?since=N is the reconnect-replay contract. ---
    if (rest.indexOf("doc/") === 0 && blockStore) {
      var tail = rest.slice(4); // "<id>" | "<id>/change" | "<id>/changes" | "<id>/import" | "<id>/snapshot"
      var slash = tail.indexOf("/");
      var docId = decodeURIComponent(slash >= 0 ? tail.slice(0, slash) : tail);
      var op = slash >= 0 ? tail.slice(slash + 1) : "";
      if (!docId) return sendJson(res, 400, { ok: false, error: "missing doc id" });
      if (op === "" && method === "GET") {
        // ticket 22: a guest on a review link reads ONLY the PINNED checkpoint snapshot
        // (frozen, never in-progress churn) -- an unpinned guest is denied (defence-in-depth
        // behind the issue-time pin requirement); everyone else reads the live materialized doc.
        if (req.__principal && req.__principal.kind === "guest") {
          var cpid = req.__principal.scope && req.__principal.scope.checkpointId;
          if (cpid == null) return sendJson(res, 403, { ok: false, error: "review link is not pinned to a snapshot" });
          var pinned = blockStore.checkpointSnapshot(cpid);
          return pinned ? sendJson(res, 200, { ok: true, doc: pinned, pinned: true }) : sendJson(res, 404, { ok: false, error: "pinned snapshot missing" });
        }
        var mat = blockStore.materializeDoc(docId);
        return mat ? sendJson(res, 200, { ok: true, doc: mat }) : sendJson(res, 404, { ok: false, error: "no such doc" });
      }
      // --- review comments (ticket 23): anchored to stable block ids; shared both ways ---
      if (op === "comments" && method === "GET" && review) {
        var exists = function (bid) { return blockStore.blockContent(docId, bid) !== null; };
        return sendJson(res, 200, { ok: true, comments: review.commentsFor(docId, exists) });
      }
      if (op === "comments" && method === "POST" && review) return withJsonBody(req, res, function (body) {
        if (!body.blockId) return sendJson(res, 400, { ok: false, error: "missing blockId" });
        var r = review.addComment(docId, body.blockId, req.__principal, body.body, body.threadId);
        if (blockStore.blockContent(docId, body.blockId) === null) r.orphaned = true; // anchor already gone -> surfaced, not dropped
        return sendJson(res, 200, r);
      });
      if (op.indexOf("comments/") === 0 && method === "POST" && review) {
        var seg = op.split("/"); // comments/<threadId>/resolve
        if (seg[2] === "resolve") return withJsonBody(req, res, function (body) {
          return sendJson(res, 200, review.resolveThread(decodeURIComponent(seg[1]), body.resolved !== false));
        });
      }
      // --- review-link management + audit (ticket 24) ---
      if (op === "links" && method === "GET" && identity) {
        return sendJson(res, 200, identity.listLinks(req.__principal, docId));
      }
      if (op === "links" && method === "POST" && identity) return withJsonBody(req, res, function (body) {
        var r = identity.issueLink(req.__principal, { docId: docId, checkpointId: body.checkpointId, version: body.version, mode: body.mode, displayName: body.displayName, expiresAt: body.expiresAt });
        return sendJson(res, r.ok ? 200 : 403, r);
      });
      if (op.indexOf("links/") === 0 && method === "DELETE" && identity) {
        return sendJson(res, 200, identity.revokeLink(req.__principal, decodeURIComponent(op.slice(6))));
      }
      if (op === "import" && method === "POST") return withJsonBody(req, res, function (body) {
        return sendJson(res, 200, { ok: true, result: blockStore.importDoc(docId, body.doc || body, body.author) });
      });
      if (op === "change" && method === "POST") return withJsonBody(req, res, function (body) {
        if (!body.blockId) return sendJson(res, 400, { ok: false, error: "missing blockId" });
        var ch = blockStore.applyChange(docId, body.blockId, body.patch, body.author);
        if (!ch.ok) return sendJson(res, 404, ch); // unknown block -> not silently dropped
        return sendJson(res, 200, { ok: true, change: ch });
      });
      if (op === "changes" && method === "GET") {
        var since = 0;
        (query.split("&")).forEach(function (kv) { var p = kv.split("="); if (p[0] === "since") since = parseInt(decodeURIComponent(p[1] || "0"), 10) || 0; });
        return sendJson(res, 200, { ok: true, since: since, changes: blockStore.changesSince(since, docId) });
      }
      if (op === "snapshot" && method === "POST") return readBody(req, function (buf) {
        var author = null; try { author = (JSON.parse((buf || Buffer.from("{}")).toString("utf8")) || {}).author; } catch (e) {}
        return sendJson(res, 200, { ok: true, snapshot: blockStore.takeSnapshot(docId, author) });
      });
      // --- checkpoints + rollback time-axis (ticket 04) ---
      if (op === "checkpoints" && method === "GET") {
        return sendJson(res, 200, { ok: true, checkpoints: blockStore.listCheckpoints(docId) });
      }
      if (op === "checkpoint" && method === "POST") return withJsonBody(req, res, function (body) {
        var cp = blockStore.createCheckpoint(docId, body.name, body.author);
        return cp.ok ? sendJson(res, 200, { ok: true, checkpoint: cp }) : sendJson(res, 400, cp);
      });
      if (op === "restore" && method === "POST") return withJsonBody(req, res, function (body) {
        var rr = blockStore.restoreCheckpoint(docId, body.checkpointId, body.author);
        return rr.ok ? sendJson(res, 200, { ok: true, restore: rr }) : sendJson(res, 404, rr);
      });
      // --- single-block history + revert-in-place (ticket 04) ---
      // "block/<blockId>/history" (GET) | "block/<blockId>/revert" (POST)
      if (op.indexOf("block/") === 0) {
        var bparts = op.slice(6).split("/");
        var blockId = decodeURIComponent(bparts[0] || "");
        var baction = bparts[1] || "";
        if (!blockId) return sendJson(res, 400, { ok: false, error: "missing block id" });
        if (baction === "history" && method === "GET") {
          return sendJson(res, 200, { ok: true, history: blockStore.blockHistory(docId, blockId) });
        }
        if (baction === "revert" && method === "POST") return withJsonBody(req, res, function (body) {
          var rv = blockStore.revertBlock(docId, blockId, body.toSeq, body.author);
          return rv.ok ? sendJson(res, 200, { ok: true, revert: rv }) : sendJson(res, 404, rv);
        });
        return sendJson(res, 405, { ok: false, error: "method not allowed" });
      }
      return sendJson(res, 405, { ok: false, error: "method not allowed" });
    }

    return sendJson(res, 404, { ok: false, error: "unknown API route" });
  };
}

// Create an http.Server. opts: { store? , blockStore? , dbPath? , config }. When a
// dbPath is given the block-addressable store (ticket 03) is opened on the SAME file,
// mounting the /api/doc/* routes below the API. Pass blockStore:null to opt out.
function createServer(opts) {
  opts = opts || {};
  var config = opts.config || { mode: "local" };
  // Real wall clock in operation (tests inject opts.now). Without this, session/token
  // expiry (expires_at <= now()) would never fire if an operator omitted a clock.
  if (opts.now == null) opts.now = function () { return Date.now(); };
  // In server mode a link-signing secret is MANDATORY -- never fall back to the module's
  // in-repo dev default, or guest review-link HMACs would be forgeable. Hard-fail startup.
  if (config.mode === "server" && opts.dbPath && !opts.hasOwnProperty("identity") && !config.linkSecret) {
    throw new Error("verso-server: config.linkSecret is required in server mode (guest review-link signing) -- set it in the config file.");
  }
  var store = opts.store || createStore(opts.dbPath);
  var blockStore = opts.hasOwnProperty("blockStore")
    ? opts.blockStore
    : (opts.dbPath ? createBlockStore(opts.dbPath, {}) : null);
  // Live-collaboration hub (ticket 08). Created always, but DORMANT unless mode==="server":
  // the hub fans out nothing in local mode, and createSyncRoutes returns an inert object
  // with no 'upgrade' handler -- so the desktop app never grows a collaboration surface.
  // Locks (ticket 10) are authoritative only in server mode; in local mode there is one
  // user, so the hub auto-grants (no lockManager) -- the solo experience is unchanged.
  var lockManager = (blockStore && config.mode === "server") ? createLockManager({ now: opts.now }) : null;
  var presence = (blockStore && config.mode === "server") ? createPresence({ now: opts.now, ttlMs: config.presenceTtlMs }) : null;
  // Identity (tickets 17/18/20): server mode only, on the same on-disk store. Dormant in
  // local mode (a single implicit owner). Injected so tests can pass a shared instance.
  var identity = opts.hasOwnProperty("identity") ? opts.identity
    : ((opts.dbPath && config.mode === "server") ? createIdentity({ dbPath: opts.dbPath, now: opts.now, linkSecret: config.linkSecret, sessionTtlMs: config.sessionTtlMs }) : null);
  // The corporate authentication rung (ticket 19): OIDC (Entra / AD FS) or IIS IWA, chosen
  // per DEPLOYMENT from the config file, never at build time. Null means this deployment runs
  // on local accounts alone -- the always-works floor -- which is also what a half-configured
  // rung falls back to rather than half-starting.
  // The structured log (platform-pivot 31): errors, auth events and promotions, one JSON object
  // per line, to a FILE the site's own collector reads. Nothing here opens an outbound connection.
  var opsLog = opts.opsLog || ops.createLog({
    file: config.logFile || (opts.dbPath ? require("node:path").join(require("node:path").dirname(opts.dbPath), "verso-server.log") : null)
  });
  var rung = opts.hasOwnProperty("rung") ? opts.rung
    : ((identity && config.mode === "server") ? authRungs.createRung(config, { now: opts.now }) : null);
  // Review comments (ticket 23): server mode only, on the same on-disk store.
  var review = opts.hasOwnProperty("review") ? opts.review
    : ((opts.dbPath && config.mode === "server") ? createReview({ dbPath: opts.dbPath, now: opts.now }) : null);
  var hub = blockStore ? createSyncHub(blockStore, { mode: config.mode, now: opts.now, lockManager: lockManager, presence: presence, review: review }) : null;
  // The sync wire resolves each connection through the SAME identity boundary as /api --
  // an anonymous /sync connection is rejected; the connection carries the resolved role.
  var sync = hub ? createSyncRoutes(hub, config, function (req) { return principalOf(req, identity, config, rung); }) : null;
  // Lease reaper (ticket 12): reclaims a vanished holder's stale lock, then broadcasts the
  // freed lock.state so peers can re-acquire. Server mode only; timer opt-in (unref'd).
  var reaper = (lockManager && hub) ? createReaper(lockManager, {
    now: opts.now, graceMs: config.lockGraceMs,
    onReclaim: function (freed) {
      var docs = {}; freed.forEach(function (f) { docs[f.docId] = true; });
      Object.keys(docs).forEach(function (docId) {
        hub.fanOut(docId, hub.envelope("lock.state", docId, null, null, null, (opts.now || function () { return 0; })(), { locks: lockManager.stateFor(docId), reclaimed: true }), null);
      });
    }
  }) : null;
  var server = http.createServer(makeHandler(store, config, blockStore, sync, identity, review, rung, { lockManager: lockManager, dbPath: opts.dbPath, log: opsLog }));
  if (sync && !sync.dormant) server.on("upgrade", sync.upgrade); // wss:// only in server mode
  server.__store = store;
  server.__blockStore = blockStore;
  server.__hub = hub;
  server.__sync = sync;
  server.__identity = identity;
  server.__rung = rung;
  server.__review = review;
  server.__lockManager = lockManager;
  server.__reaper = reaper;
  server.__config = config;
  server.__opsLog = opsLog;
  if (reaper && config.reaperIntervalMs) reaper.start(config.reaperIntervalMs); // opt-in periodic sweep
  return server;
}

// Start listening. In local mode bind loopback only; in server mode bind the
// configured host. The mode flag is the ONLY behavioural difference.
function startServer(config, cb) {
  var server = createServer({ dbPath: config.dbPath, config: config });
  var host = config.mode === "server" ? (config.host || "0.0.0.0") : "127.0.0.1";
  // Honour port 0 (ephemeral, used by tests) -- `|| 4790` would wrongly treat 0 as unset.
  var port = config.port != null ? config.port : 4790;
  server.listen(port, host, function () { if (cb) cb(server, host, port); });
  return server;
}

module.exports = {
  createServer: createServer, makeHandler: makeHandler, startServer: startServer,
  buildBootstrap: buildBootstrap, assembleLibrary: assembleLibrary, libraryDocId: libraryDocId,
  hydrationSet: hydrationSet, topicDoc: topicDoc, ops: ops
};
