/*
 * scripts/build-dict.js -- generate the bundled spellcheck dictionary (src/spellcheck-dict.js).
 *
 *   node scripts/build-dict.js [wordlist-path]
 *
 * Builds a Bloom filter over an English word list (default: /usr/share/dict/words) and
 * emits it as a classic-script global (window.VersoSpellDict = { m, k, bits<base64> }).
 * A Bloom filter is the right structure for spellcheck: fixed size, O(1) membership, and
 * its only error mode is a FALSE POSITIVE (reports a word present when it isn't) -> at
 * worst a rare misspelling is not flagged. It NEVER produces a false negative, so a word
 * that IS in the dictionary is never wrongly flagged as a typo. Air-gap friendly: the
 * output is a plain data blob, no deps, loads from file://.
 *
 * The runtime (src/spellcheck.js) recomputes the SAME hash positions, so the double-hash
 * scheme here (h1 + i*h2, 32-bit FNV-1a x2) is the contract between the two files.
 */
"use strict";
var fs = require("fs");
var path = require("path");

var SRC = process.argv[2] || "/usr/share/dict/words";
var OUT = path.join(__dirname, "..", "src", "spellcheck-dict.js");
var TARGET_FPR = 0.002; // 0.2% -> ~1 in 500 typos slips through; correct words always pass

// ---- the hash contract (MUST match src/spellcheck.js) --------------------
function fnv1a(str, seed) {
  var h = seed >>> 0;
  for (var i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}
function positions(word, m, k) {
  var h1 = fnv1a(word, 0x811c9dc5);
  var h2 = fnv1a(word, 0xdeadbeef) | 1; // odd -> full period with m power-of-two-ish
  var out = new Array(k);
  for (var i = 0; i < k; i++) out[i] = ((h1 + Math.imul(i, h2)) >>> 0) % m;
  return out;
}

// ---- read + normalise the word list --------------------------------------
var raw = fs.readFileSync(SRC, "utf8").split(/\r?\n/);
var words = Object.create(null);
var n = 0;
for (var i = 0; i < raw.length; i++) {
  var w = raw[i].toLowerCase();
  // keep pure-alpha words (and internal apostrophes stripped) of a sane length
  w = w.replace(/[^a-z]/g, "");
  if (w.length < 2 || w.length > 22) continue;
  if (!words[w]) { words[w] = 1; n++; }
}
// A seed of common words the 1934-era system list lacks: modern/tech terms + British-ise
// spellings (incl. the -ize roots web2 itself omits, e.g. "prioritize"). Inflections
// (-s/-ed/-ing/-ation) are handled by the runtime morphology, so only the base is needed.
[// modern / tech / UI
 "ok", "email", "website", "online", "offline", "login", "logout", "signup", "signin",
 "checkbox", "dropdown", "app", "apps", "url", "urls", "faq", "faqs", "info", "todo",
 "wifi", "username", "chatbot", "workflow", "dataset", "tooltip", "hyperlink",
 "screenshot", "dashboard", "onboarding", "walkthrough", "dropdowns", "smartphone",
 "smartphones", "multimedia", "wearable", "wearables", "livestream", "podcast",
 "podcasts", "ebook", "ebooks", "webinar", "webinars", "toolkit", "printout",
 // British / Commonwealth -ise + -ize roots web2 omits
 "prioritize", "prioritise", "customize", "customise", "summarize", "summarise",
 "minimize", "minimise", "maximize", "maximise", "utilize", "utilise", "categorize",
 "categorise", "personalize", "personalise", "standardize", "standardise", "optimize",
 "optimise", "analyze", "analyse", "emphasize", "emphasise", "familiarize", "familiarise",
 "specialize", "specialise", "realize", "realise", "organize", "organise", "recognize",
 "recognise", "authorize", "authorise", "memorize", "memorise", "visualize", "visualise",
 "finalize", "finalise", "modernize", "modernise", "centralize", "centralise",
 // British -our / -re / -ce that trip the -our/-re rules or are simply absent
 "colour", "colours", "behaviour", "behaviours", "favour", "favourite", "favourites",
 "labour", "neighbour", "flavour", "honour", "humour", "rumour", "odour", "vapour",
 "centre", "centres", "metre", "metres", "litre", "litres", "theatre", "fibre",
 "defence", "offence", "licence", "practise", "programme", "catalogue", "dialogue",
 // common workplace / L&D vocabulary
 "workplace", "workplaces", "stakeholder", "stakeholders", "deliverable", "deliverables",
 "upskill", "reskill", "mentorship", "wellbeing", "learnings"].forEach(function (w) {
  if (!words[w]) { words[w] = 1; n++; }
});

// ---- size the filter -----------------------------------------------------
var m = Math.ceil((-n * Math.log(TARGET_FPR)) / (Math.LN2 * Math.LN2));
var k = Math.max(1, Math.round((m / n) * Math.LN2));
var bytes = Math.ceil(m / 8);
var bits = new Uint8Array(bytes);

var keys = Object.keys(words);
for (var j = 0; j < keys.length; j++) {
  var pos = positions(keys[j], m, k);
  for (var p = 0; p < k; p++) { var b = pos[p]; bits[b >>> 3] |= (1 << (b & 7)); }
}

var b64 = Buffer.from(bits).toString("base64");
var out =
  "/* GENERATED by scripts/build-dict.js from " + SRC + " -- do not edit by hand.\n" +
  "   Bloom filter over " + n + " English words (FPR ~= " + TARGET_FPR + ").\n" +
  "   Editor chrome ONLY: loaded by index.html for the spellchecker; never bundled in a\n" +
  "   SCORM export and never read by render(). */\n" +
  "window.VersoSpellDict = { n: " + n + ", m: " + m + ", k: " + k + ", bits: \"" + b64 + "\" };\n";
fs.writeFileSync(OUT, out);
console.log("wrote " + OUT + "  (" + n + " words, m=" + m + " bits, k=" + k + ", " + bytes + " bytes -> " + b64.length + " b64 chars)");
